### ISSUE TITLE
Thunderbird Autoconfig HTTPS

### ISSUE THREAD

**Issue by axoroll7** [fleaz/MDEC#1]
Hello,
When I tested Thunderbird, HTTPS redirection to the autoconfig XML file worked. You said in your README it should not be the case. Maybe it was in old versions ?

**Comment by fleaz** [comment]
This is poorly formulated in the readme: Autoconfig (the system from Mozilla Thunderbird) will start with plain HTTP and use it if it's avaiable via http but will also follow any redirect to HTTPS. Autodiscover on the other hand will never accept or try to use plain HTTP and requires HTTPS.

I will rephrase this part, thanks :)

**Comment by axoroll7** [comment]
> This is poorly formulated in the readme: Autoconfig (the system from Mozilla Thunderbird) will start with plain HTTP and use it if it's avaiable via http but will also follow any redirect to HTTPS. Autodiscover on the other hand will never accept or try to use plain HTTP and requires HTTPS.
> 
> I will rephrase this part, thanks :)

Thank you ! I will close this issue
